const A='https://github.com/nelsonsia27/TeaShop/blob/main/';
const raw=p=>A+p+'?raw=true';
const assets={
 cups:{Small:raw('cup-small.png'),Medium:raw('cup-medium.png'),Large:raw('cup-large.png')},
 flavorIcons:{'Classic Milk Tea':raw('classic.png'),'Brown Sugar Milk Tea':raw('brown-sugar.png'),'Jasmine Green Tea':raw('jasmine.png'),'Taro Milk Tea':raw('taro.png'),'Chocolate Milk Tea':raw('chocolate.png')},
 flavorFill:{'Classic Milk Tea':raw('classic-fill.png'),'Brown Sugar Milk Tea':raw('brown-sugar-fill.png'),'Jasmine Green Tea':raw('Jasmine-fill.png'),'Taro Milk Tea':raw('Taro-fill.png'),'Chocolate Milk Tea':raw('Chocolate-fill.png')},
 iceFill:{'100%':raw('100-ice-fill.png'),'50%':raw('50-ice-fill.png'),'30%':raw('30-ice-fill.png')},
 toppings:{'Egg Pudding':raw('egg-pudding.png'),'Taro Balls':raw('taro-balls.png'),'Ice Cream':raw('ice-cream.png'),'Grass Jelly':raw('grass-jelly.png'),'Cheese Foam':raw('cheese-foam.png'),'Coconut Jelly':raw('coconut-jelly.png')},
 toppingFill:{'Egg Pudding':raw('egg-pudding-fill.png'),'Taro Balls':'https://github.com/nelsonsia27/TeaShop/blob/main/taro-ball-fill%20(2).png?raw=true','Grass Jelly':raw('grass-jelly-fill.png'),'Coconut Jelly':raw('coconut-jelly-fill.png'),'Ice Cream':raw('ice-cream-fill.png'),'Cheese Foam':raw('cheese-foam-fill.png')},
 sparkle:raw('sparkle.gif')
};
const data={
 flavor:['Classic Milk Tea','Brown Sugar Milk Tea','Jasmine Green Tea','Taro Milk Tea','Chocolate Milk Tea'],
 size:['Small','Medium','Large'], ice:['100%','50%','30%','0%'], sugar:['100%','70%','50%','30%','0%'],
 toppings:['Egg Pudding','Taro Balls','Ice Cream','Grass Jelly','Cheese Foam','Coconut Jelly']
};
const prices={Small:45,Medium:55,Large:65,topping:10};
const steps=['Flavor','Size','Ice','Sugar','Toppings'];
let stepIndex=0, selected=null, order={flavor:null,size:null,ice:null,sugar:null,toppings:[]}, mode='customerChoose';
const $=id=>document.getElementById(id);
const els=['intro','game','final','progress','customerPanel','cashierPanel','customerSentence','cashierSentence','customerChoices','cashierChoices','customerActions','confirmChoice','changeChoice','customerBubble','cashierBubble','customerHint','cashierHint','drinkBuilder','receipt','playAgain'].reduce((o,id)=>(o[id]=$(id),o),{});
$('startBtn').onclick=()=>{show('game');initStep();}; els.playAgain.onclick=()=>location.reload();
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');}
function setReader(role){els.customerPanel.classList.toggle('active-reader',role==='customer');els.cashierPanel.classList.toggle('active-reader',role==='cashier');els.customerPanel.classList.toggle('frozen',role==='cashier'||role==='none');els.cashierPanel.classList.toggle('frozen',role==='customer'||role==='none');}
function progress(){els.progress.innerHTML=steps.map((s,i)=>`<span class="step-pill ${i<stepIndex?'done':i===stepIndex?'current':''}">${s}</span>`).join('');}
function sentenceTemplate(kind,val='________'){const v=`<span class="filled">${val}</span>`; if(kind==='flavor')return `Hi! I want a ${v}, please.`; if(kind==='size')return `I want a ${v}, please.`; if(kind==='ice')return `${v} ice, please.`; if(kind==='sugar')return `${v} sugar, please.`; return `Yes, I want ${order.toppings[0]?`<span class="filled">${order.toppings[0]}</span>`:'________'} and ${order.toppings[1]?`<span class="filled">${order.toppings[1]}</span>`:'________'}.`;}
function cashierPrompt(kind){if(kind==='flavor')return 'Hello! Welcome to our tea shop. What would you like to drink?'; if(kind==='size')return 'Okay! What size do you want? Small, medium, or large?'; if(kind==='ice')return 'What ice level would you like? We have 100%, 50%, 30%, or 0%.'; if(kind==='sugar')return 'And what sugar level? We have 100%, 70%, 50%, 30%, or 0%.'; return 'Do you want to add any toppings? They are 10 dollars each.';}
function kind(){return ['flavor','size','ice','sugar','toppings'][stepIndex];}
function initStep(){progress();selected=null;mode='customerChoose';let k=kind();setReader('cashier');els.customerHint.textContent='Wait and listen.';els.cashierHint.textContent='Read, then tap the sentence box.';els.customerActions.classList.add('hidden');els.customerChoices.innerHTML='';els.cashierChoices.innerHTML='';els.customerSentence.innerHTML=sentenceTemplate(k);els.cashierSentence.textContent=cashierPrompt(k);markBubble('cashier');}
function markBubble(role){els.customerBubble.classList.toggle('ready-read',role==='customer');els.cashierBubble.classList.toggle('ready-read',role==='cashier');}
els.cashierBubble.onclick=()=>{if(mode==='customerChoose' && els.cashierBubble.classList.contains('ready-read')){markBubble('none');setReader('customer');els.customerHint.textContent='Choose, confirm, read, then tap sentence.';els.cashierHint.textContent='Wait for customer.';renderCustomerChoices();}};
els.customerBubble.onclick=()=>{if(mode==='customerRead' && els.customerBubble.classList.contains('ready-read')){markBubble('none');mode='cashierChoose';setReader('cashier');els.customerHint.textContent='Wait for cashier.';els.cashierHint.textContent='Select the matching picture.';renderCashierChoices();}};
function renderCustomerChoices(){let k=kind(), list=data[k]; if(k==='toppings'){els.customerChoices.innerHTML=list.map(x=>`<button class="choice-card" data-val="${x}">${x}</button>`).join('');} else {els.customerChoices.innerHTML=list.map(x=>`<button class="choice-card" data-val="${x}">${x}</button>`).join('');} els.customerChoices.querySelectorAll('button').forEach(b=>b.onclick=()=>chooseCustomer(b));}
function chooseCustomer(btn){let k=kind(), val=btn.dataset.val;if(k==='toppings'){if(order.toppings.includes(val)){order.toppings=order.toppings.filter(x=>x!==val);btn.classList.remove('selected');}else if(order.toppings.length<2){order.toppings.push(val);btn.classList.add('selected');}selected=order.toppings.length===2?order.toppings.slice():null;els.customerActions.classList.toggle('hidden',!selected);els.customerSentence.innerHTML=sentenceTemplate(k);}else{selected=val;els.customerChoices.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b===btn));els.customerActions.classList.remove('hidden');els.customerSentence.innerHTML=sentenceTemplate(k,val);}}
els.changeChoice.onclick=()=>{selected=null;if(kind()==='toppings')order.toppings=[];els.customerActions.classList.add('hidden');els.customerSentence.innerHTML=sentenceTemplate(kind());renderCustomerChoices();};
els.confirmChoice.onclick=()=>{let k=kind();if(!selected)return;if(k!=='toppings')order[k]=selected;els.customerActions.classList.add('hidden');mode='customerRead';markBubble('customer');els.customerHint.textContent='Read your sentence aloud, then tap the sentence box.';};
function imgFor(k,v){if(k==='flavor')return assets.flavorIcons[v]; if(k==='size')return assets.cups[v]; if(k==='toppings')return assets.toppings[v]; if(k==='ice')return v==='0%'?null:assets.iceFill[v]; return raw('sugar.png');}
function renderCashierChoices(){let k=kind(), list=data[k];els.cashierChoices.innerHTML=list.map(v=>`<button class="choice-card" data-val="${v}">${imgFor(k,v)?`<img src="${imgFor(k,v)}" alt="${v}">`:`<div class="small-icon">🚫</div>`}<div class="label">${v}${k==='ice'?' Ice':''}</div></button>`).join('');els.cashierChoices.querySelectorAll('button').forEach(b=>b.onclick=()=>checkCashier(b));}
function checkCashier(btn){let k=kind(), val=btn.dataset.val;let correct=k==='toppings'?order.toppings.includes(val):order[k]===val;if(!correct){btn.classList.add('wrong');setTimeout(()=>btn.classList.remove('wrong'),450);return;}btn.classList.add('correct');if(k==='toppings'){let correctCount=[...els.cashierChoices.querySelectorAll('.correct')].filter(b=>order.toppings.includes(b.dataset.val)).length;if(correctCount<2)return;}setTimeout(()=>cashierRead(),350);}
function cashierRead(){mode='cashierRead';markBubble('cashier');els.cashierSentence.innerHTML=summarySentence();els.cashierHint.textContent='Read your sentence aloud, then tap the sentence box.';}
els.cashierBubble.addEventListener('click',()=>{if(mode==='cashierRead'&&els.cashierBubble.classList.contains('ready-read')){markBubble('none');stepIndex++; if(stepIndex>=steps.length)return finish(); initStep();}});
function summarySentence(){let k=kind(); if(k==='flavor')return `Alright, one ${order.flavor}.`; if(k==='size')return `${order.size}. Got it.`; if(k==='ice')return `${order.ice} ice. Okay.`; if(k==='sugar')return `${order.sugar} sugar. Okay.`; return `Great! I will add ${order.toppings[0]} and ${order.toppings[1]}.`;}
function total(){return prices[order.size]+order.toppings.length*prices.topping;}
function finish(){show('final');renderDrink();renderReceipt();}
function layer(src,cls,delay=''){return src?`<img class="drink-layer ${cls} ${delay}" src="${src}" alt="">`:'';}
function renderDrink(){let bottoms=order.toppings.filter(t=>['Egg Pudding','Taro Balls','Grass Jelly','Coconut Jelly'].includes(t));let tops=order.toppings.filter(t=>['Ice Cream','Cheese Foam'].includes(t));els.drinkBuilder.innerHTML=layer(assets.flavorFill[order.flavor],'flavor','delay1')+bottoms.map((t,i)=>layer(assets.toppingFill[t],'bottom',`delay${i+2}`)).join('')+layer(assets.iceFill[order.ice],'ice','delay3')+tops.map((t,i)=>layer(assets.toppingFill[t],'top',`delay${i+4}`)).join('')+layer(assets.cups[order.size],'cup','delay5')+layer(assets.sparkle,'sparkle','delay5');}
function receiptRow(icon,title,value,img=true){return `<div class="receipt-row"><div>${img&&icon?`<img src="${icon}" alt="">`:`<div class="small-icon">${icon||''}</div>`}</div><div><b>${title}</b><span>${value}</span></div></div>`;}
function renderReceipt(){els.receipt.innerHTML=receiptRow(assets.cups[order.size],'Cup Size',order.size)+receiptRow(assets.flavorIcons[order.flavor],'Flavor',order.flavor)+receiptRow(order.ice==='0%'?'🚫':assets.iceFill[order.ice],'Ice',`${order.ice} Ice`,order.ice!=='0%')+receiptRow('🍬','Sugar',`${order.sugar} Sugar`,false)+order.toppings.map(t=>receiptRow(assets.toppings[t],'Topping',t)).join('')+`<div class="total">Total: ${total()} NTD</div>`;}
